// <auto-generated />
using System;
using HotelRepoPatternAssignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelRepoPatternAssignment.Migrations
{
    [DbContext(typeof(HotelDBContext))]
    [Migration("20240902094413_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelRepoPatternAssignment.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            HotelName = "Thaj Mahal"
                        },
                        new
                        {
                            HotelId = 2,
                            HotelName = "Munthaj Mahal"
                        },
                        new
                        {
                            HotelId = 3,
                            HotelName = "Andhra Mahal"
                        });
                });

            modelBuilder.Entity("HotelRepoPatternAssignment.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("RooomType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 11,
                            HotelId = 1,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        },
                        new
                        {
                            RoomId = 12,
                            HotelId = 2,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        },
                        new
                        {
                            RoomId = 13,
                            HotelId = 3,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        },
                        new
                        {
                            RoomId = 14,
                            HotelId = 1,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        },
                        new
                        {
                            RoomId = 15,
                            HotelId = 2,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        },
                        new
                        {
                            RoomId = 16,
                            HotelId = 3,
                            Price = 12000m,
                            RoomNumber = 101,
                            RooomType = "Luxury"
                        });
                });

            modelBuilder.Entity("HotelRepoPatternAssignment.Models.Room", b =>
                {
                    b.HasOne("HotelRepoPatternAssignment.Models.Hotel", "Hotel")
                        .WithMany("Room")
                        .HasForeignKey("HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelRepoPatternAssignment.Models.Hotel", b =>
                {
                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
